### PR TITLE
Added Slovene locale

### PR DESCRIPTION
**Pull request by plankobostjan**

### CODE REVIEW

**Review by JoeSchubert — COMMENTED** [review]
Did you intend to leave the $headerMsg (line 13) in english?

**Comment by JoeSchubert** [comment]
Your PR should not include the merge and locale. Definitely recommend keeping them, but in a different change/PR as that branch is a WIP.

**Comment by roenw** [comment]
@yoinx I could just squash the commits during merging, yeah?

**Comment by plankobostjan** [comment]
@yoinx No, I didn't intend to leave the $headerMsg (line 13) in English. It's fixed now.

Also, what exactly do you mean by:

> Your PR should not include the merge and locale

?

**Comment by JoeSchubert** [comment]
These are from different branches. They'll make things a bit messy when roenw goes to accept the PR. 

For example. You want to fix the 2 issues in master got the uninstall. You should push those to a branch in your fork (could be master, could be a branch called "fix_uninstall, doesn't really matter) you make the PR for that vs roenw's master. Then you should reset back to a HEAD that is even with roenw's repo. Checkout a branch for the translations. Make your changes and submit a PR for that change.

The reason is that you have to keep the branches with your changes for the PR to stay open. If you pull from roenw over top of your changes from master, it'll close your PR. plus it just makes things cleaner, even if it might end up with "conflicts" it should do so less often.

As this PR is right now, I think roenw would have to merge it all to accept it (or part of it and reject the rest) so for the WIP locales  stuff, it would just kinda get lost.

**Comment by JoeSchubert** [comment]
@roenw you could squash them. Like I said, things will start to get messy though when accepting PRs that are changing things from multiple branches into one.

**Comment by plankobostjan** [comment]
@yoinx thanks for the explanation. It helped a lot. I did what you said and am now on the same commit in my locales-beta branch as @roenw's locales-beta. I will now open a new PR.

PR closed

**Pull request closed without merging**
