### PR TITLE
Setup fixes

### PR DESCRIPTION
**Pull request by JoeSchubert**
Just some general fixes that I came across while attempting to install this on my pi.

### CODE REVIEW

**Comment by roenw** [comment]
Thanks for this; I'll merge once I get language support committed, hopefully sometime tonight.

**Comment by JoeSchubert** [comment]
no worries. I was looking at a way to automate the lighttpd.conf change as well. It looks like executing 
`
sed -i /etc/lighttpd/lighttpd.conf -re 's/(server.error-handler-404[^"]*")([^"]*)(")/\1index\.php\3/'
`
should do it cleanly. This wouldn't help people without lighttpd, but since it's the default for pihole, it would probably be easy enough to just check for the file first.

**Comment by roenw** [comment]
Yeah. When I was writing the setup instructions/script I accidentally thought nginx was the default webserver for some reason. It seems a lot of people are having trouble with webserver setup, so automating this would make life a lot easier for them.

**Comment by JoeSchubert** [comment]
As per the commit message for the first one in that second set, these would make the installation simply: 

cd ~/ && wget -O setup.php https://apps.roen.us/pipass/setup && sudo php setup.php

I still need to get the sed bit in though.

**Comment by JoeSchubert** [comment]
Ok... I got it figured out, I think. The first command should handle changing anything set as BLOCKINGMODE=whatever, to BLOCKINGMODE=IP or add BLOCKINGMODE=IP if it isn't in the file. The second one should handle modifing the server.error-handler-404 line. I would recommend backing these files up (cp file file.bak) then you should be able to call these in an exec wrapper. That *should* make it all so that the previous one liner would be everything that someone would need to do to install this on a stock pihole install. I'm not the best with PHP though, or I'd try to slap it together.. and I'm done for the night.

```
sudo sed -i '/^BLOCKINGMODE=/{h;s/=.*/=IP/};${x;/^$/{s//BLOCKINGMODE=IP/;H};x}' /etc/pihole/pihole-FTL.conf

sudo sed -i /etc/lighttpd/lighttpd.conf -re 's/(server.error-handler-404[^"]*")([^"]*)(")/\1index\.php\3/'
```

**Comment by roenw** [comment]
I don’t know jack about regex or anything you just wrote so I’ll try it out and hope it works. I’ll merge this later (I’m busy right now and there are conflicts I have to resolve)

Thanks for all of your help!

**Pull request merged**
